server:
  port: 8080
  servlet:
    context-path: /demo
################\u524D\u7AEF\u89C6\u56FE\u5C55\u793A\u91C7\u7528jsp####################
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
